### ISSUE TITLE
Denied Access to mysql

### ISSUE THREAD

**Issue by dangerfish96** [jgoerzen/docker-ampache#1]
I had an issue where the access to mysql as root would be denied.
The issue is seen here: https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost

To fix this I propose the following change: https://pastebin.com/yvezMVee

**Comment by jgoerzen** [comment]
I think this would work; I need to understand the security implications of this better.  I guess the larger question is: why?  There's already an ampache user/password set up that should be easy enough to use.  Can you elaborate for me?

**Comment by dangerfish96** [comment]
Ah, now I understand. I tried to create a new user ampache with password ampache, using root and a blank password and got an error because of that... I misunderstood the tutorial, sorry for that
